# general
seed: 42
workers: 8
dataset_dir: "/home/chenyannan/fast-differential-privacy-main/examples/image_classification/data"


# train options
batch_size: 280
mini_bs: 140
image_size: 224
test_image_size: 256
start_epoch: 80
epochs: 800
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
clipping_style: "all-layer"
r_conv: 4
r_proj: 16


# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 256
model_path: "save/Img-10-pretrain-transform-cluster"
reload: True

# loss options
learning_rate: 0.0003
project_lr: 0.0006
resnet_lr: 0.006
downsample_lr: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
