# general
seed: 42
workers: 8
dataset_dir: "/home/chenyannan/fast-differential-privacy-main/examples/image_classification/data"


# train options
batch_size: 65
mini_bs: 65
image_size: 224
start_epoch: 0
epochs: 18
local_epoch: 8
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
epsilon: 8
clip_bound: 1.6
clipping_style: "all-layer"
n_clients: 200
sample_ratio: 0.02


# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/Img-10-FL-clientlevel-test"
reload: True

# loss options
learning_rate: 0.0005
project_lr: 0.001
resnet_lr: 0.007
global_lr: 1
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
