# general
seed: 17
workers: 8
dataset_dir: "/home/chenyannan/fast-differential-privacy-main/examples/image_classification/data"


# train options
batch_size: 100
mini_bs: 100
image_size: 224
test_image_size: 256
start_epoch: 0
epochs: 55
local_epoch: 6
dataset: "CIFAR-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
epsilon: 8
clip_bound: 1.8
clipping_style: "all-layer"
n_clients: 600
sample_ratio: 0.5
r_conv: 6
r_proj: 16


# model options
resnet: "ResNet18_lora" # ResNet18 / ResNet34 / ResNet50 / ResNet18_Adapter/ ResNet18_lora
feature_dim: 128
model_path: "save/Cifar-10-DPFL-ResNet18-blur-lus-kl-threshold-lorabegin2"
reload: False

# loss options
learning_rate: 0.004
project_lr: 0.05
resnet_lr: 0.14
downsample_lr: 0.05
global_lr: 1.06
weight_decay: 0.00001
instance_temperature: 0.5
cluster_temperature: 1.0
momentum: 0.3
miu: 0.05
relation_t: 1
relation_t2: 1
bn_sparsity: 0.9
linear_sparsity: 0.75
alpha: 1
smooth_K: 6
smooth_loss_radius: 2
smooth_step: 0
loss_KL: 0.5
kl_threshold: 0.4