# general
seed: 4
workers: 8
dataset_dir: "/home/chenyannan/fast-differential-privacy-main/examples/image_classification/data"


# train options
batch_size: 100
mini_bs: 100
image_size: 224
test_image_size: 256
start_epoch: 0
epochs: 1
local_epoch: 8
dataset: "CIFAR-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
epsilon: 8
clipping_style: "all-layer"
n_clients: 600
r_conv: 6
r_proj: 16

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/Cifar-10-central"
reload: False

# loss options
learning_rate: 0.0003
project_lr: 0.0006
resnet_lr: 0.006
downsample_lr: 0.0002
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
